import random
import string

# print(string.ascii_lowercase)
# print(string.ascii_uppercase)
# print(string.ascii_letters)
# print(string.digits)
# print(string.punctuation)
pass_len = 12
charValues = string.ascii_letters + string.digits + string.punctuation

print("\n")
print("Password generated by the 1st method !!!")
password =""
for i in range(pass_len):
    password += random.choice(charValues)

print("Your random password is:", password)

print("\n")

print("Password generated by the 2nd method !!!")
# List comprehension [function for i in range(n)]
password = "".join([random.choice(charValues) for i in range(pass_len)])
print("Your random password is:", password)
print("\n")